# Generated by Django 3.2.5 on 2022-03-17 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
